### ISSUE TITLE
【Document】In Apple Silicon we need replace Mysql with MariaDB

### ISSUE THREAD

**Issue by zxt2012bs** [docker/docs#12634] opened 2021-04-08 04:02 UTC
### Problem description

In Apple Silicon we need replace Mysql with MariaDB, because mysql is not available in Apple Silicon

### Problem location

https://docs.docker.com/language/python/develop/#connect-the-application-to-the-database

https://docs.docker.com/language/python/develop/#use-compose-to-develop-locally

### Project version(s) affected

If not Mariadb , users will not able to go on this develop step

### Suggestions for a fix

my config:
***
import mysql.connector
import json
from flask import Flask

app = Flask(__name__)

@app.route('/')
def hello_world():
  return 'Hello, Docker!'

@app.route('/widgets')
def get_widgets() :
  mydb = mysql.connector.connect(
    host="mariadb",
    user="root",
    password="p@ssw0rd1",
    database="inventory"
  )
  cursor = mydb.cursor()

  cursor.execute("SELECT * FROM widgets")

  row_headers=[x[0] for x in cursor.description] #this will extract row headers

  results = cursor.fetchall()
  json_data=[]
  for result in results:
    json_data.append(dict(zip(row_headers,result)))

  cursor.close()

  return json.dumps(json_data)

@app.route('/initdb')
def db_init():
  mydb = mysql.connector.connect(
    host="mariadb",
    user="root",
    password="p@ssw0rd1"
  )
  cursor = mydb.cursor()

  cursor.execute("DROP DATABASE IF EXISTS inventory")
  cursor.execute("CREATE DATABASE inventory")
  cursor.close()

  mydb = mysql.connector.connect(
    host="mariadb",
    user="root",
    password="p@ssw0rd1",
    database="inventory"
  )
  cursor = mydb.cursor()

  cursor.execute("DROP TABLE IF EXISTS widgets")
  cursor.execute("CREATE TABLE widgets (name VARCHAR(255), description VARCHAR(255))")
  cursor.close()

  return 'init database'

if __name__ == "__main__":
  app.run(host ='0.0.0.0')

***

***
version: '3.8'

services:
 web:
  build:
   context: .
  ports:
  - 5000:5000
  volumes:
  - ./:/app

 mariadb:
  image: mariadb
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=p@ssw0rd1
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:
***

**Comment by craig-osterhout** [comment] 2022-10-13 21:33
Thanks for sharing the issue and suggested fix. Closing as duplicate of #14136

**Closed by craig-osterhout** 2022-10-13 21:33 UTC
Labels: area/get-started
