### ISSUE TITLE
Rails 7 Example

### ISSUE THREAD

**Issue by cmdrkeene** [docker/docs#16422] opened 2023-01-03 16:23 UTC
File: [samples/rails.md](https://docs.docker.com/samples/rails/)

Please update this sample for Rails 7.

Rails 7 ships with sqlite by default.

Having a working option for this with a persisted volume would be helpful.

While common, postgresql is not the default database for Rails.

Thank you!

**Comment by craig-osterhout** [comment] 2023-01-03 19:57
Thanks for sharing the issue. Closing as duplicate of https://github.com/docker/awesome-compose/issues/315

**Closed by craig-osterhout** 2023-01-03 19:57 UTC
Labels: area/Samples
