### ISSUE TITLE
MacOS Instructions incorrect.

### ISSUE THREAD

**Issue by cyberwombat** [docker/docs#16439] opened 2023-01-05 01:26 UTC
File: [desktop/uninstall.md](https://docs.docker.com/desktop/uninstall/)

There is no such thing as `/Applications/Docker.app/Contents/MacOS/uninstall`

**Comment by mat007** [comment] 2023-01-05 06:03
Hi! Thanks, I’ll just close this as a duplicate of https://github.com/docker/docs/issues/16307.

**Closed by mat007** 2023-01-05 06:03 UTC
