### ISSUE TITLE
[404]: /desktop/win/configuring-wsl

### ISSUE THREAD

**Issue by hercial61** [docker/docs#18764] opened 2023-11-23 01:12 UTC
### Location

https://docs.docker.com

### Broken link

https://docs.docker.com/desktop/win/configuring-wsl?uuid=54194B43-C440-4BBE-B76B-D4A867D6C7CA

### Comment

a broken link

**Comment by aevesdocker** [comment] 2023-11-23 09:06
Closing issue as I cannot reproduce

**Closed by aevesdocker** 2023-11-23 09:06 UTC
Labels: status/triage
