### ISSUE TITLE
Error in Docker Playground

### ISSUE THREAD

**Issue by Gene-Dana** [docker/docs#16567] opened 2023-01-20 15:40 UTC
File: [get-started/04_sharing_app.md](https://docs.docker.com/get-started/04_sharing_app/)

Hi there 👋🏼 After step 5 I received this warning and was unable to move forward

```
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
```

**Comment by iamanshul360** [comment] 2023-01-20 17:30
Here are the few solutions:
Solution 1:  Add the flag -platform linux/arm64. Example:
docker run -d \
    --platform linux/amd64 \
    --network todo-app --network-alias mysql \
    -v todo-mysql-data:/var/lib/mysql \
    -e MYSQL_ROOT_PASSWORD=secret \
    -e MYSQL_DATABASE=todos \
    mysql:5.7

Solution 2: You can try to add this command while building docker images
--platform linux/amd64

**Comment by iamanshul360** [comment] 2023-01-20 17:34
You can try to add this command while creating docker images:
--platform linux/amd64
Example:
docker run -d \
    --platform linux/amd64
    --network todo-app --network-alias mysql \
    -v todo-mysql-data:/var/lib/mysql \
    -e MYSQL_ROOT_PASSWORD=  \
    -e MYSQL_DATABASE=  \

**Comment by craig-osterhout** [comment] 2023-01-20 22:05
Thanks for sharing the issue. Closing as dupe of #14546.

**Closed by craig-osterhout** 2023-01-20 22:05 UTC
