### ISSUE TITLE
Windows Defender detecting virus in Docker Desktop 4.17.0.99724

### ISSUE THREAD

**Issue by grickmarshall** [docker/docs#16977] opened 2023-03-26 01:44 UTC
https://community.flexera.com/t5/AdminStudio-Forum/Docker-Desktop-4-17-0-99724-from-Package-Feed-Module-detected/m-p/270686

While this is a command line install, it has the same information I get from a gui install. Windows Defender interrupts the installation:
INSTALLATION FAILED:
Manifest extraction failed: Operation did not complete successfully because the file contains a virus or potentially unwanted software.

   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

Plus I get a Windows Defender popup with a virus detected.

**Comment by grickmarshall** [comment] 2023-03-26 02:05
Downloaded 4.16.3 and installed successfully without issue.

**Comment by thaJeztah** [comment] 2023-03-26 19:11
Thanks for reporting! Closing this as duplicate of https://github.com/docker/for-win/issues/13335

**Closed by thaJeztah** 2023-03-26 19:11 UTC
