### ISSUE TITLE
[404]: /compose/extends/

### ISSUE THREAD

**Issue by Egor-oop** [docker/docs#17786] opened 2023-07-20 20:25 UTC
### Location

https://www.google.com/

### Broken link

https://docs.docker.com/compose/extends/

### Comment

The title of this page is _"Share Compose configurations between files and projects"_ on Google

**Comment by collinstevens** [comment] 2023-07-21 16:24
Duplicate of #17767

**Closed** 2023-07-21 19:23 UTC
Labels: status/triage
