### ISSUE TITLE
Docker Desktop for Mac uninstall instructions are incorrect

### ISSUE THREAD

**Issue by Mnkras** [docker/docs#16411] opened 2022-12-29 02:13 UTC
File: [desktop/uninstall.md](https://docs.docker.com/desktop/uninstall/)

The doc specifies: `<path to Docker app>/Contents/MacOS/uninstall` can be executed, but that binary does not exist
Docker Desktop: 4.15.0 (93002)

```
$ ls -l /Applications/Docker.app/Contents/MacOS/                                                                                                                                               
total 359072
-rwxr-xr-x@ 1 mkrasnow  admin  13095280 Dec  1 02:48 Docker
drwxr-xr-x@ 3 mkrasnow  admin        96 Dec  1 02:48 Docker Desktop.app
-rwxr-xr-x@ 1 mkrasnow  admin   7442720 Dec  1 02:48 com.docker.admin
-rwxr-xr-x@ 1 mkrasnow  admin  48623888 Dec  1 02:48 com.docker.backend
-rwxr-xr-x@ 1 mkrasnow  admin  13064832 Dec  1 02:48 com.docker.dev-envs
-rwxr-xr-x@ 1 mkrasnow  admin  15697248 Dec  1 02:48 com.docker.diagnose
-rwxr-xr-x@ 1 mkrasnow  admin  17821216 Dec  1 02:48 com.docker.driver.amd64-linux
-rwxr-xr-x@ 1 mkrasnow  admin  18496976 Dec  1 02:48 com.docker.extensions
-rwxr-xr-x@ 1 mkrasnow  admin   8089216 Dec  1 02:48 com.docker.osxfs
-rwxr-xr-x@ 1 mkrasnow  admin   6126128 Dec  1 02:48 com.docker.url-handler
-rwxr-xr-x@ 1 mkrasnow  admin  10436080 Dec  1 02:48 com.docker.virtualization
-rwxr-xr-x@ 1 mkrasnow  admin  10673600 Dec  1 02:48 install
-rwxr-xr-x@ 1 mkrasnow  admin   3812640 Dec  1 02:48 qcow-tool
-rwxr-xr-x@ 1 mkrasnow  admin  10442128 Dec  1 02:48 vpnkit-bridge
```

**Comment by mat007** [comment] 2023-01-02 07:24
Hi! Thanks, I’ll just close this as a duplicate of https://github.com/docker/docs/issues/16307.

**Closed by mat007** 2023-01-02 07:24 UTC
Labels: area/Desktop
