### ISSUE TITLE
uninstall script is not available as documented

### ISSUE THREAD

**Issue by booltype** [docker/docs#16356] opened 2022-12-16 12:52 UTC
File: [desktop/uninstall.md](https://docs.docker.com/desktop/uninstall/)

It seems `uninstall` is not available on macOS version 4.15, uninstallation as described is not possible.

**Comment by mat007** [comment] 2022-12-16 13:20
Hi! Thanks, I’ll just close this as a duplicate of #16307

**Closed by mat007** 2022-12-16 13:20 UTC
