### ISSUE TITLE
[Python docs feedback]

### ISSUE THREAD

**Issue by 1561316811** [docker/docs#13584] opened 2021-09-22 09:41 UTC
### Problem description
when i run "  docker build --tag python-docker . "
I met this: ERROR: Could not find a version that satisfies the requirement cloud-init==19.1 (from versions: none)
ERROR: No matching distribution found for cloud-init==19.1

### Problem location

- I saw a problem on the following URL: <URL>https://docs.docker.com/language/python/build-images/

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by craig-osterhout** [comment] 2022-10-12 22:21
Closing as duplicate of #13576

**Closed by craig-osterhout** 2022-10-12 22:21 UTC
Labels: area/get-started
