### ISSUE TITLE
nvidia-container-runtime is deprecated

### ISSUE THREAD

**Issue by Mereks** [docker/docs#18699] opened 2023-11-16 14:29 UTC
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

https://github.com/NVIDIA/nvidia-container-runtime has been replaced by https://github.com/NVIDIA/nvidia-container-toolkit

### Location

https://docs.docker.com/config/containers/resource_constraints/

### Suggestion

Update documents with instructions for new software

**Comment by thaJeztah** [comment] 2023-11-27 20:38
Thanks for reporting; looks like this is a duplicate of https://github.com/docker/docs/issues/18479

**Closed by thaJeztah** 2023-11-27 20:38 UTC
Labels: area/engine, status/triage
