### ISSUE TITLE
spring-petclinic docker-compose.dev.yml

### ISSUE THREAD

**Issue by lbdecastro** [docker/docs#14068] opened 2022-01-06 04:15 UTC
Hi! I am experiencing this issue when following the guide in docker compose of language-specific (java)

cmd: docker-compose -f docker-compose.dev.yml up --build
error: standard_init_linux.go:228: exec user process caused: no such file or directory

any ideas? thank you

**Comment by tcordon** [comment] 2022-02-15 16:45
Hi!

Today i have had the same error.

Check that all files have linux line-endings. 
I had one file with windows line-endings, and Docker throwed that error all the time.

I have lost a loot of time to resolve this.

It had been off great help if Docker's logging had add the name of the file that is missing or the output of the script/file that throwed that error.

Greetings!

**Comment by craig-osterhout** [comment] 2022-10-17 21:42
Hi @lbdecastro, thanks for sharing the issue. Did changing the line endings fix the issue?

**Comment by craig-osterhout** [comment] 2022-10-19 22:26
Closing as duplicate of #13930

**Closed by craig-osterhout** 2022-10-19 22:26 UTC
Labels: area/get-started, status/need-more-info
