### ISSUE TITLE
SQL command missing in Docker example?

### ISSUE THREAD

**Issue by pwdirks** [docker/docs#16741] opened 2023-02-18 03:05 UTC
File: [get-started/07_multi_container.md](https://docs.docker.com/get-started/07_multi_container/)

Step 5 under "Run your app with MySQL" shows the SQL query to inspect the database:

> select * from todo_items;

However this gave me an error:

> ERROR 1046 (3D000): No database selected

What I first had to do was select a database for use:

> use todos

... and after that the query command above worked.  Perhaps you could add "use todos" as a command to run before the "select" command?

**Comment by aslamahemad** [comment] 2023-02-18 04:54
submitted the PR #16743

**Comment by aslamahemad** [comment] 2023-02-18 04:55
Submitted the PR #16743

**Comment by craig-osterhout** [comment] 2023-02-21 17:59
@pwdirks, thanks for sharing the issue.
It looks like the previous command in the tutorial specifies the usage of the todos database.
`docker exec -it <mysql-container-id> mysql -p todos`
If you connected to the container in an alternate way, the database may have not been selected.

When using the above command to connect to the container, did you receive any error?
If yes, what does the output of `status;` in the mysql prompt show?

**Comment by aslamahemad** [comment] 2023-02-22 06:40
Hi @craig-osterhout, I got the same error as of @pwdirks. I think I had misplaced my commands. Even I am not able to reproduce the error now. Anyways, I apologize for the inconvenience. I am closing the PR.

**Closed** 2023-02-22 15:54 UTC
Labels: area/get-started, status/need-more-info
