### ISSUE TITLE
[404]: /opensource/project/who-written-for/

### ISSUE THREAD

**Issue by minshaf998** [docker/docs#18196] opened 2023-09-14 16:46 UTC
### Location

In CONTRIBUTING.md file

### Broken link

https://docs.docker.com/opensource/project/who-written-for/

```[tasklist]
### Tasks
```

**Comment by minshaf998** [comment] 2023-09-14 17:00
Found this link from contributing.md file on docker-cli cloned from here.
master branch

**Comment by craig-osterhout** [comment] 2023-09-14 20:02
Thanks for sharing the issue. Closing as duplicate of https://github.com/docker/cli/issues/4036

**Closed by craig-osterhout** 2023-09-14 20:02 UTC
Labels: status/triage
