### ISSUE TITLE
broken link in contribution tips and guidelines, review process.

### ISSUE THREAD

**Issue by desmond3th** [docker/docs#18602] opened 2023-11-06 09:22 UTC
### Location

https://github.com/docker/cli/blob/9cb175f02af75061a5a19ca9597bd1f5e7dd7d32/CONTRIBUTING.md#quick-contribution-tips-and-guidelines

### Broken link

https://docs.docker.com/opensource/workflow/make-a-contribution/

### Comment

At this particular line : 
"Our contributor's guide explains [the review process we use for simple changes] "

_No response_

**Comment by craig-osterhout** [comment] 2023-11-06 16:23
Thanks for sharing the issue. Closing as duplicate of https://github.com/docker/cli/issues/4036

**Closed by craig-osterhout** 2023-11-06 16:23 UTC
Labels: status/triage
