### ISSUE TITLE
MacOS uninstall executable does not exist.

### ISSUE THREAD

**Issue by gideonite** [docker/docs#16288] opened 2022-12-06 16:26 UTC
File: [desktop/uninstall.md](https://docs.docker.com/desktop/uninstall/)

- I ran the default installation of Docker on a Mac with a M1 Pro Chip. 
- `/Applications/Docker.app/Contents/MacOS/` exists but there is no `uninstall` executable, as indicated in the documentation file above.

**Comment by mat007** [comment] 2022-12-06 17:09
Hi, thanks for the issue.
I’ll close it as a duplicate of https://github.com/docker/for-mac/issues/6598
This will be fixed in the next Docker Desktop release.

**Closed by mat007** 2022-12-06 17:09 UTC
