### ISSUE TITLE
[404]: /go/buildk

### ISSUE THREAD

**Issue by 0-th** [docker/docs#21318] opened 2024-11-02 17:49 UTC
### Location

`docker build` cli

### Broken link

https://docs.docker.com/go/buildk

### Comment

running the `docker build` command to build an image for a dockerfile with a mount directive.

I get the following message:
```
Step 11/14 : RUN --mount=type=cache,target=/root/.cache/pip     --mount=type=bin
d,source=requirements.txt,target=/tmp/dev.txt     python -m pip install -r /tmp/
dev.txt
the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildk
it/ to learn how to build images with BuildKit enabled
```

the attached link to buildkit is broken.

**Comment by thaJeztah** [comment] 2024-11-02 21:29
It looks like the output in your terminal was wrapped: the URL continues on the next line (the `it/` is part of the URL, so the location your looking for is; https://docs.docker.com/go/buildkit/

**Comment by thaJeztah** [comment] 2024-11-02 21:30
I'll close this ticket as this is not a bug on the docs website, but feel free to continue the conversation

**Closed by thaJeztah** 2024-11-02 21:30 UTC
Labels: status/triage
