### ISSUE TITLE
[Python docs feedback]

### ISSUE THREAD

**Issue by dschlimovich** [docker/docs#14155] opened 2022-01-18 14:41 UTC
### Problem description

The cache export feature in Github is no longer supported for the Docker driver.

### Problem location

- I saw a problem at the following URL: <Add URL>

- I couldn't find the information I wanted. I expected to find it near the following URL <Add the URL and briefly describe how we can improve the existing content>

- Other: <Add details that can help us understand the issue>
Other:  When running the "Optimizing the workflow" step from the "CI/CD for your application" page. GitHub's workflow throws the following error:
```
Error: buildx failed with: error: cache export feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
```
### Project version(s) affected

It affects the Python guide.

**Comment by pankeshpatel** [comment] 2022-06-21 21:14
I have been facing the similar issues when I use `github actions` for python.

I have not found information on Google.

**Comment by craig-osterhout** [comment] 2022-10-12 22:01
Closing as duplicate of #14749

**Closed by craig-osterhout** 2022-10-12 22:01 UTC
Labels: area/get-started
